# Generated by Django 4.2.28 on 2026-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_invitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role_assigned',
            field=models.CharField(choices=[('admin', 'Product Owner (Admin)'), ('contributeur', 'Scrum Master (Contributor)'), ('read-only', 'Developer (Read-Only)')], default='read-only', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contributeur', 'Contributor'), ('read-only', 'Read-Only')], default='read-only', max_length=20),
        ),
    ]
