# Generated by Django 4.2.28 on 2026-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_invitation_role_assigned_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role_assigned',
            field=models.CharField(choices=[('member', 'Project member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
