# Generated by Django 4.2.29 on 2026-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invitation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contributeur', 'Contributor'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
