# Generated by Django 4.2.29 on 2026-04-06 22:55

from django.db import migrations, models


def rename_contributeur_forward(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(role='contributeur').update(role='contributor')


def rename_contributeur_backward(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(role='contributor').update(role='contributeur')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_role'),
    ]

    operations = [
        # First rename existing data rows before altering the field choices
        migrations.RunPython(rename_contributeur_forward, rename_contributeur_backward),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contributor', 'Contributor'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
