# Generated by Django 4.2.29 on 2026-04-04 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_alter_post_date_posted'), ('blog', '0003_project_ticket_delete_post'), ('blog', '0004_ticket_epic_ticket_issue_type_alter_ticket_priority'), ('blog', '0005_alter_ticket_description'), ('blog', '0006_project_capacity_mode_project_code_prefix_and_more'), ('blog', '0007_alter_project_capacity_mode_and_more'), ('blog', '0008_alter_ticket_issue_type_sprint_ticket_sprint'), ('blog', '0009_sprint_uniq_active_sprint_per_project'), ('blog', '0006_projectmember'), ('blog', '0010_merge_0006_projectmember_0009_sprint_uniq_active_sprint_per_project'), ('blog', '0011_alter_project_capacity_mode_and_more'), ('blog', '0012_alter_ticket_options_ticket_backlog_order_and_more'), ('blog', '0013_sprint_objective_alter_project_capacity_mode_and_more'), ('blog', '0014_sprint_capacity'), ('blog', '0015_sprint_story_points_capacity'), ('blog', '0016_alter_projectmember_role'), ('blog', '0017_ticket_initial_load_ticket_remaining_load_and_more'), ('blog', '0018_sprint_ticket_template_ticket_color_ticketattachment'), ('blog', '0019_tag_ticket_tags'), ('blog', '0020_ticketlink_ticketlink_unique_ticket_link')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('capacity_mode', models.CharField(choices=[('GLOBAL', 'CapacitÃ© globale'), ('PER_USER', 'CapacitÃ© par user')], default='GLOBAL', max_length=20)),
                ('code_prefix', models.CharField(help_text='PrÃ©fixe unique du projet, ex: CRM.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le code projet doit contenir uniquement des lettres/numÃ©ros en majuscule.', regex='^[A-Z0-9][A-Z0-9_-]*$')])),
                ('end_date', models.DateField(null=True)),
                ('global_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sprint_duration_days', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(null=True)),
                ('workload_unit', models.CharField(choices=[('MAN_DAYS', 'Man-days'), ('MAN_HOURS', 'Man-hours'), ('STORY_POINTS', 'Story points')], default='MAN_DAYS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifie'), ('ACTIVE', 'Actif'), ('CLOSED', 'Cloture')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='blog.project')),
            ],
            options={
                'ordering': ['project', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='blog.project')),
                ('epic', models.ForeignKey(blank=True, limit_choices_to={'issue_type': 'EPIC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='blog.ticket')),
                ('issue_type', models.CharField(choices=[('EPIC', 'Epic'), ('STORY', 'Story'), ('BUG', 'Bug')], default='STORY', max_length=20)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='blog.sprint')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('project',), name='uniq_active_sprint_per_project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='capacity_mode',
            field=models.CharField(choices=[('GLOBAL', 'CapacitÃƒÂ© globale'), ('PER_USER', 'CapacitÃƒÂ© par user')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_prefix',
            field=models.CharField(help_text='PrÃƒÂ©fixe unique du projet, ex: CRM.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le code projet doit contenir uniquement des lettres/numÃƒÂ©ros en majuscule.', regex='^[A-Z0-9][A-Z0-9_-]*$')]),
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['backlog_order', 'date_posted', 'id']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='backlog_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='capacity_mode',
            field=models.CharField(choices=[('GLOBAL', 'Capacité globale'), ('PER_USER', 'Capacité par user')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_prefix',
            field=models.CharField(help_text='Préfixe unique du projet, ex: CRM.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le code projet doit contenir uniquement des lettres/numéros en majuscule.', regex='^[A-Z0-9][A-Z0-9_-]*$')]),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifié'), ('ACTIVE', 'Actif'), ('CLOSED', 'Clôturé')], default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='sprint',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='capacity_mode',
            field=models.CharField(choices=[('GLOBAL', 'Global capacity'), ('PER_USER', 'Capacity per user')], default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_prefix',
            field=models.CharField(help_text='Unique project prefix, e.g. CRM.', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='The project code must contain only uppercase letters, numbers, underscores, or hyphens.', regex='^[A-Z0-9][A-Z0-9_-]*$')]),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='sprint',
            name='capacity_mode',
            field=models.CharField(choices=[('GLOBAL', 'Global capacity'), ('PER_USER', 'Capacity per user')], default='GLOBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sprint',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Global sprint capacity in story points.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='story_points',
            field=models.PositiveIntegerField(default=0, help_text='Used for stories and bugs only.'),
        ),
        migrations.CreateModel(
            name='SprintUserCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capacities', to='blog.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'unique_together': {('sprint', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='blog.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='initial_load',
            field=models.PositiveIntegerField(default=0, help_text='Initial effort estimate for stories, bugs and tasks.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remaining_load',
            field=models.PositiveIntegerField(default=0, help_text='Remaining effort for stories, bugs and tasks.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('EPIC', 'Epic'), ('STORY', 'Story'), ('BUG', 'Bug'), ('TASK', 'Task')], default='STORY', max_length=20),
        ),
        migrations.AddField(
            model_name='sprint',
            name='ticket_template',
            field=models.CharField(choices=[('ticket_card', 'Template 1 - Classic'), ('ticket_card_alt', 'Template 2 - Accent'), ('ticket_card_compact', 'Template 3 - Compact')], default='ticket_card', help_text='Display template used for all tickets in this sprint.', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='color',
            field=models.CharField(blank=True, help_text='Hex colour code for epic tickets.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour code (e.g. #AABBCC).', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('normalized_name', models.CharField(editable=False, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='blog.tag'),
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('BLOCKED_BY', 'Blocked by'), ('RELATES_TO', 'Relates to')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='blog.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='blog.ticket')),
            ],
            options={
                'ordering': ['link_type', 'source_ticket_id', 'target_ticket_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketlink',
            constraint=models.UniqueConstraint(fields=('source_ticket', 'target_ticket', 'link_type'), name='unique_ticket_link'),
        ),
    ]
