# Generated by Django 4.2.29 on 2026-04-04 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_scope_tags_to_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='code_prefix',
            field=models.CharField(help_text="Unique project prefix (e.g., 'CRM').", max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Project code: uppercase, numbers, underscore, hyphen only.', regex='^[A-Z0-9][A-Z0-9_-]*$')]),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='ticket_template',
            field=models.CharField(choices=[('ticket_card', 'Template 1 - Classic'), ('ticket_card_alt', 'Template 2 - Accent'), ('ticket_card_compact', 'Template 3 - Compact')], default='ticket_card', max_length=30),
        ),
        migrations.AlterField(
            model_name='sprintusercapacity',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Story point capacity for this user in sprint.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Display name (may contain spaces).', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(editable=False, help_text='Internal normalized form (lowercase, trimmed).', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(help_text='Project this tag belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.project'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color for epic tickets.', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Valid hex: #AABBCC', regex='^#(?:[0-9a-fA-F]{6})$')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='initial_load',
            field=models.PositiveIntegerField(default=0, help_text='Effort estimate for stories, bugs, tasks.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remaining_load',
            field=models.PositiveIntegerField(default=0, help_text='Remaining effort.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='story_points',
            field=models.PositiveIntegerField(default=0, help_text='For stories and bugs only.'),
        ),
    ]
