# Generated by Django 4.2.29 on 2026-04-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_project_options_alter_projectmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPointsScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_type', models.CharField(choices=[('fibonacci', 'Fibonacci (1, 2, 3, 5, 8, 13, 21, 34, 55, 89)'), ('powers_of_2', 'Powers of 2 (1, 2, 4, 8, 16, 32)'), ('linear', 'Linear (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)'), ('custom', 'Custom values')], default='fibonacci', help_text='Predefined scheme or custom values.', max_length=20)),
                ('custom_values', models.JSONField(blank=True, default=list, help_text="Custom list of allowed story point values (JSON array). Used when scheme_type is 'custom'.")),
                ('project', models.OneToOneField(help_text='Project this scheme belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='story_points_scheme', to='blog.project')),
            ],
            options={
                'verbose_name_plural': 'Story points schemes',
            },
        ),
        migrations.AddConstraint(
            model_name='storypointsscheme',
            constraint=models.UniqueConstraint(fields=('project',), name='one_scheme_per_project'),
        ),
    ]
