# Generated by Django 4.2.29 on 2026-04-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_storypointsscheme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storypointsscheme',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='storypointsscheme',
            name='one_scheme_per_project',
        ),
        migrations.RemoveField(
            model_name='storypointsscheme',
            name='custom_values',
        ),
        migrations.AlterField(
            model_name='storypointsscheme',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_points_scheme', to='blog.project'),
        ),
        migrations.AlterField(
            model_name='storypointsscheme',
            name='scheme_type',
            field=models.CharField(choices=[('fibonacci', 'fibonacci'), ('powers_2', 'powers_2'), ('linear', 'linear')], default='fibonacci', max_length=20),
        ),
    ]
