# Generated by Django 4.2.29 on 2026-04-06 01:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_storypointsscheme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(help_text='Git repository URL (e.g., https://github.com/user/repo)', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('repository_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea'), ('local', 'Local Repository')], default='local', help_text='Type of Git hosting service', max_length=20)),
                ('access_token', models.CharField(blank=True, help_text='API token for private repos (GitHub/GitLab personal token)', max_length=500, null=True)),
                ('is_private', models.BooleanField(default=False, help_text='Whether the repository is private')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time repository was queried for updates', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this repository config was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('project', models.OneToOneField(help_text='Project linked to this Git repository', on_delete=django.db.models.deletion.CASCADE, related_name='git_repository', to='blog.project')),
            ],
            options={
                'verbose_name': 'Git Repository',
                'verbose_name_plural': 'Git Repositories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'repository_type'], name='blog_gitrep_project_760b0c_idx')],
            },
        ),
    ]
