# Generated by Django 4.2.29 on 2026-04-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_gitrepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(max_length=254)),
                ('commit_date', models.DateTimeField()),
                ('commit_url', models.URLField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('git_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='blog.gitrepository')),
            ],
            options={
                'verbose_name': 'Git Commit',
                'verbose_name_plural': 'Git Commits',
                'ordering': ['-commit_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('git_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='blog.gitcommit')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit_links', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_links', to='blog.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Commit Link',
                'verbose_name_plural': 'Ticket Commit Links',
                'ordering': ['-linked_at'],
                'unique_together': {('ticket', 'git_commit')},
            },
        ),
        migrations.AddIndex(
            model_name='gitcommit',
            index=models.Index(fields=['git_repository', '-commit_date'], name='blog_gitcom_git_rep_b224c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gitcommit',
            unique_together={('sha', 'git_repository')},
        ),
    ]
